# The Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.

[[ 1., 0., 0.],
 [ 0., 1., 2.]]

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

### ndarray.ndim
   the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.
### ndarray.shape
   the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.
### ndarray.size
   the total number of elements of the array. This is equal to the product of the elements of shape.
### ndarray.
   an object describing the type of the elements in the array. One can create or specify ’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
### ndarray.itemsize
   the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray..itemsize.
### ndarray.data
   the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities. 

In [2]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.ndim

2

In [5]:
a.shape

(3, 5)

In [6]:
a.size

15

In [9]:
a.dtype
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [11]:
a.data

In [12]:
type(a)

numpy.ndarray

In [14]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [15]:
type(b)

numpy.ndarray

## Array Creation


There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [16]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
b = np.array([1.5,2.5,3.5])
b

array([1.5, 2.5, 3.5])

In [19]:
b.dtype

dtype('float64')

A "frequent error consists" in calling "array" with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [20]:
# WRONG
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [21]:
# RIGHT
a = np.array([1,2,3,4])

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [22]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
b = np.array([(1.5,2,3), (4,5,6), (7,8,9)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

The type of the array can also be explicitly specified at creation time:

In [24]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
x = np.array([(1,2,3), (4,5,6)])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [49]:
y = np.array([(1,2,3), (7,8,9)])
y

array([[1, 2, 3],
       [7, 8, 9]])

In [50]:
np.ones_like(y)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [52]:
z = np.array([(12,13,14), (15,16,17)])
z

array([[12, 13, 14],
       [15, 16, 17]])

In [53]:
np.empty_like(z)

array([[1718182757,  543450473, 1919181921],
       [ 544437093, 1679848289, 1852401253]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [30]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [36]:
np.arange(start=0,stop=2,step=0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [37]:
# num is number of elements in the array here 9 elements
# retstep - return (samples, step), where step is the spacing between samples.
np.linspace(start=0,stop=2,num=9,endpoint=False,retstep=True)

(array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
        1.11111111, 1.33333333, 1.55555556, 1.77777778]), 0.2222222222222222)

In [3]:
from numpy import pi
x = np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
f = np.sin(x)
f

array([0.        , 0.24740396, 0.47942554, 0.68163876, 0.84147098,
       0.94898462, 0.99749499, 0.98398595, 0.90929743])

Random values in a given shape.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [55]:
np.random.rand(3,4)

array([[0.60245625, 0.85276617, 0.68846526, 0.17873406],
       [0.62779619, 0.68896463, 0.14104263, 0.88208241],
       [0.4639523 , 0.49252321, 0.67823105, 0.00859853]])

Return a sample (or samples) from the “standard normal” distribution.

If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [56]:
np.random.randn()

0.5684277753391394

In [58]:
np.random.randn(3,4)

array([[-0.39007798, -0.48558634,  0.8754451 , -1.47735753],
       [-1.31159832,  0.00954509, -0.51004078,  1.32987864],
       [ 1.72541928,  0.78658348,  0.39785238,  1.76978512]])

For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu

In [5]:
2.5 * np.random.randn(3,4) + 1

array([[ 3.14652358, -3.64523242,  2.24700713, -2.16623701],
       [-0.53098666,  3.02776502, -1.71481148,  1.82484619],
       [-1.72995504, -1.56826167,  4.34721195, -0.75325534]])

## Printing Arrays

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [7]:
# 1d array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [10]:
# 2d array
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
# 3d array
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [14]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [15]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [22]:
# To disable this behaviour and force NumPy to print the entire array, 
# you can change the printing options using set_printoptions.
np.set_printoptions(threshold='nan')

## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [26]:
a = np.array([20,30,40,50])

In [27]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [28]:
c = a-b
c

array([20, 29, 38, 47])

In [29]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [30]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [31]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method:

In [32]:
A = np.array([[1,1],[0,1]])
A

array([[1, 1],
       [0, 1]])

In [33]:
B = np.array([[2,0],[3,4]])
B

array([[2, 0],
       [3, 4]])

In [34]:
# Elementwise product
A*B

array([[2, 0],
       [0, 4]])

In [35]:
# Matrix product
A.dot(B)

array([[5, 4],
       [3, 4]])

In [36]:
# Another matrix product
np.dot(A,B)

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [40]:
a = np.ones((2,3), dtype = int)
b = np.random.random((2,3))

In [41]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [43]:
b += a
b

array([[6.77696666, 6.0991957 , 6.83499424],
       [6.10309803, 6.96203627, 6.24175706]])

In [44]:
# b is not automatically converted to integer type
a += b
a

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [45]:
f = np.ones(3, dtype = np.int32)
g = np.linspace(0,pi,3)

In [47]:
f

array([1, 1, 1])

In [48]:
g

array([0.        , 1.57079633, 3.14159265])

In [49]:
g.dtype.name

'float64'

In [50]:
h = f+g
h

array([1.        , 2.57079633, 4.14159265])

In [52]:
h.dtype.name

'float64'

In [54]:
i = np.exp(h*1j)
i

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [55]:
i.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [56]:
a = np.random.random((2,3))
a

array([[0.3913368 , 0.17505088, 0.45534457],
       [0.35980152, 0.71767701, 0.42661344]])

In [57]:
a.sum()

2.5258242300760863

In [58]:
a.min()

0.17505088222902776

In [59]:
a.max()

0.7176770143669262

In [62]:
a.mean()

0.420970705012681

In [64]:
a.var()

0.025724072396844693

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array

In [67]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
# sum of each column
b.sum(axis=0)

array([12, 15, 18, 21])

In [69]:
# min of each row
b.min(axis=1)

array([0, 4, 8])

In [70]:
# cumulative sum of each row
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [71]:
B = np.arange(3)
B

array([0, 1, 2])

In [72]:
# Calculate the exponential of all elements in the input array.
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [73]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [74]:
np.std(B)

0.816496580927726

In [77]:
C = np.array([2,-1,4.], dtype='float32')
C

array([ 2., -1.,  4.], dtype=float32)

In [78]:
np.add(B,C)

array([2., 0., 6.])

In [81]:
A = np.array([[True, True], [True, False]])
A

array([[ True,  True],
       [ True, False]])

In [85]:
# Test whether all array elements along a given axis evaluate to True.
np.all(A, axis=0)

array([ True, False])

In [88]:
# Test whether any array element along a given axis evaluates to True.
# Returns single boolean unless axis is not None
# Does any row contain the element False in it
np.any(A==False, axis=1)

array([False,  True])

In [89]:
# Apply a function to 1-D slices along the given axis.
# Execute func1d(a, *args) where func1d operates on 1-D arrays and a is a 1-D slice of arr along axis.

b = np.array([[8,1,7],[4,3,9],[5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

In [91]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.apply_along_axis(np.diag,-1,c)

array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]])

In [92]:
# Returns the indices of the minimum values along an axis.
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
print(np.argmin(a))
print(np.argmin(a, axis=1))
print(np.argmin(a, axis=0))

0
[0 0]
[0 0 0]


In [97]:
print(np.argmax(a))
print(np.argmax(a, axis=0))    # returns the indices of the max element
print(np.argmax(a, axis=1))    # returns the indices of the max element along the row
a[1] = 5
print(np.argmax(a))

5
[1 1 1]
[2 2]
3


array([[0, 1, 2],
       [5, 5, 5]])